import GampRSP from '../../../GampRSP.mjs';
import {
    ensureLLM,
    summariseSpecs,
    parsePlan,
    executePlan,
} from '../utils/specPlanner.mjs';

const buildPlannerPrompt = ({ task, specs }) => {
    const instructions = [
        '# Specification Update Planner',
        'You receive a change request and the current specs snapshot.',
        'Respond ONLY with a JSON array describing the actions the GampRSP singleton should perform.',
        '',
        'Allowed actions:',
        '- createURS { "title", "description" }',
        '- updateURS { "id", "title", "description" }',
        '- retireURS { "id" }',
        '- createFS { "title", "description", "ursId", "reqId?" }',
        '- updateFS { "id", "title", "description", "ursId" }',
        '- createNFS { "title", "description", "ursId", "reqId?" }',
        '- updateNFS { "id", "title", "description", "ursId" }',
        '- createDS { "title", "description", "architecture", "ursId", "reqId" }',
        '- updateDS { "id", "description", "architecture" }',
        '- createTest { "dsId", "title", "description" }',
        '- describeFile { "dsId", "filePath", "why", "how", "what", "description", "exports":[], "dependencies":[], "sideEffects", "concurrency" }',
        '',
        '## Current Specs Snapshot',
        specs || '<empty>',
        '',
        '## Change Request',
        task || '<empty>',
        '',
        '## Response Format',
        '[{"action":"createURS","title":"...","description":"..."}]',
    ];
    return instructions.join('\n');
};

const fallbackScaffold = (prompt) => {
    const title = (prompt || 'New Requirement').split(/[\r\n\.]+/).map((entry) => entry.trim()).filter(Boolean)[0] || 'New Requirement';
    const description = prompt || 'Pending description.';
    const ursId = GampRSP.createURS(title, description);
    const fsId = GampRSP.createFS(title, description, ursId);
    const dsId = GampRSP.createDS(title, description, 'Architecture will be refined during implementation.', ursId, fsId);
    const testId = GampRSP.createTest(dsId, `${title} happy path`, 'Placeholder automated test generated by update-specs.');
    return [
        { action: 'createURS', id: ursId },
        { action: 'createFS', id: fsId },
        { action: 'createDS', id: dsId },
        { action: 'createTest', id: testId, dsId },
    ];
};

export async function action({ prompt, context }) {
    const workspaceRoot = context.workspaceRoot || process.cwd();
    GampRSP.configure(workspaceRoot);
    const llm = ensureLLM(context);
    const specsSnapshot = summariseSpecs();
    let plan = [];

    try {
        const rawPlan = await llm.executePrompt(buildPlannerPrompt({ task: prompt, specs: specsSnapshot }), {
            responseShape: 'json',
            context: { intent: 'update-specs-plan' },
        });
        plan = parsePlan(rawPlan);
    } catch (error) {
        plan = [];
        if (process.env.ACHILES_DEBUG === 'true') {
            console.warn(`[update-specs] planner failed: ${error.message}`);
        }
    }

    const outcomes = plan.length ? executePlan(plan) : fallbackScaffold(prompt);
    return {
        message: plan.length ? 'Specifications updated via planner.' : 'Specifications updated via fallback scaffold.',
        actions: outcomes,
    };
}

export default action;
