import GampRSP from '../../../GampRSP.mjs';

const buildTitle = (prompt = '') => {
    if (!prompt) {
        return 'New Requirement';
    }
    const sentences = prompt.split(/[\r\n\.]+/).map((sentence) => sentence.trim()).filter(Boolean);
    const candidate = sentences[0] || prompt.trim();
    return candidate.length > 60 ? `${candidate.slice(0, 57)}...` : candidate;
};

export async function action({ prompt, context }) {
    const workspaceRoot = context.workspaceRoot || process.cwd();
    GampRSP.configure(workspaceRoot);
    const title = buildTitle(prompt);
    const description = prompt || 'Pending description.';

    const ursId = GampRSP.createURS(title, description);
    const fsId = GampRSP.createFS(title, description, ursId);
    const dsId = GampRSP.createDS(title, description, 'Architecture will be refined during implementation.', ursId, fsId);
    const testId = GampRSP.createTest(dsId, `${title} happy path`, 'Placeholder automated test generated by update-specs.');

    return {
        message: 'Specifications updated',
        ursId,
        fsId,
        dsId,
        testId,
    };
}

export default action;
