import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { LLMAgent } from '../LLMAgents/LLMAgent.mjs';
import { envAutoConfig } from '../LLMAgents/envAutoConfig.mjs';

// Load environment variables
envAutoConfig();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CASES_DIR = path.join(__dirname, 'planAndExecute');

const COLORS = {
    RESET: "\x1b[0m",
    RED: "\x1b[31m",
    GREEN: "\x1b[32m",
    YELLOW: "\x1b[33m",
};

// Mock Tool Implementations
const TOOL_IMPLEMENTATIONS = {
    // Math
    add: async (...args) => {
        const [a, b] = args;
        return String(Number(a) + Number(b));
    },
    multiply: async (...args) => {
        const [a, b] = args;
        return String(Number(a) * Number(b));
    },
    subtract: async (a, b) => {
        return String(Number(a) - Number(b));
    },
    divide: async (a, b) => {
        const numB = Number(b);
        if (numB === 0) return "Infinity";
        return String(Number(a) / numB);
    },
    // Text
    reverse: async (...args) => {
        const [text] = args;
        return text.split('').reverse().join('');
    },
    uppercase: async (...args) => {
        const [text] = args;
        return text.toUpperCase();
    },
    lowercase: async (text) => {
        return text.toLowerCase();
    },
    length: async (text) => {
        return String(text.length);
    },
    concat: async (str1, str2) => {
        return str1 + str2;
    },
    substring: async (text, start, len) => {
        return text.substring(Number(start), Number(start) + Number(len));
    },
    contains: async (haystack, needle) => {
        return haystack.includes(needle) ? "true" : "false";
    },
    // Logic
    isEven: async (...args) => {
        const [num] = args;
        return (parseInt(num, 10) % 2 === 0) ? "true" : "false";
    },
    invert: async (...args) => {
        const [bool] = args;
        return (bool.trim() === "true") ? "false" : "true";
    },
    and: async (a, b) => {
        const boolA = a.trim() === "true";
        const boolB = b.trim() === "true";
        return (boolA && boolB) ? "true" : "false";
    },
    or: async (a, b) => {
        const boolA = a.trim() === "true";
        const boolB = b.trim() === "true";
        return (boolA || boolB) ? "true" : "false";
    },
    // Extraction
    extractEmail: async (...args) => {
        const [text] = args;
        const match = text.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/);
        return match ? match[0] : "";
    },
    getDomain: async (...args) => {
        const [email] = args;
        const parts = email.split('@');
        return parts.length > 1 ? parts[1] : "";
    }
};

async function main() {
    // Initialize Agent
    const agent = new LLMAgent({ name: 'Executor' });
    
    // Get cases
    console.log(`Reading cases from ${CASES_DIR}...`);
    const files = await fs.readdir(CASES_DIR);
    const cases = files.filter(f => f.endsWith('.json')).sort();
    
    let totalCases = 0;
    let passedCases = 0;

    for (const caseFile of cases) {
        const casePath = path.join(CASES_DIR, caseFile);
        const caseData = JSON.parse(await fs.readFile(casePath, 'utf8'));
        
        const { prompt, tools: toolDefinitions, expectedOutput } = caseData;
        
        // Construct tools object for planAndExecute
        const toolsForAgent = {};
        for (const [name, desc] of Object.entries(toolDefinitions)) {
            if (!TOOL_IMPLEMENTATIONS[name]) {
                console.warn(`Warning: No implementation for tool '${name}' in case ${caseFile}`);
            }
            toolsForAgent[name] = {
                description: desc,
                handler: TOOL_IMPLEMENTATIONS[name] || (async () => "mock_result")
            };
        }

        console.log(`\nRunning ${caseFile}...`);
        console.log(`Prompt: "${prompt}"`);

        try {
            const variables = await agent.executeSOPLangPlan(toolsForAgent, prompt, {
                onPlanGenerated: (code) => {
                    console.log(`${COLORS.YELLOW}Generated Plan:\n${code}${COLORS.RESET}`);
                }
            });
            
            // Check results
            // We check if *any* variable matches the expected value (since variable names are generated by LLM)
            let passed = false;
            const expectedKey = Object.keys(expectedOutput)[0]; // Assume 1 expected output for simplicity
            const expectedVal = expectedOutput[expectedKey];
            
            // Look for expected value in any of the final variables
            const foundEntry = Object.entries(variables).find(([k, v]) => v === expectedVal);
            
            if (foundEntry) {
                passed = true;
                console.log(`${COLORS.GREEN}✅ Passed! Found "${expectedVal}" in variable @${foundEntry[0]}${COLORS.RESET}`);
            } else {
                console.log(`${COLORS.RED}❌ Failed${COLORS.RESET}`);
                console.log(`Expected value: "${expectedVal}"`);
                console.log(`Actual variables:`, variables);
            }
            
            if (passed) passedCases++;
            
        } catch (err) {
            console.error(`${COLORS.RED}Execution Error:${COLORS.RESET}`, err);
        }
        totalCases++;
    }
    
    console.log('\n=== Summary ===');
    console.log(`Passed: ${passedCases}/${totalCases}`);
}

main().catch(console.error);
